export const StackNav = {
  //OuthScreens
  Login: 'Login',
  Terms: 'Terms',
  SignUp: 'SignUp',
  Welcome: 'Welcome',
  VerifyOtp: 'VerifyOtp',
  NewPassword: 'NewPassword',
  ForgetPassword: 'ForgetPassword',
  ResetPassword: 'ResetPassword',

  //AppStack Screens
  AppStack: 'AppStack',
  ProjectName: 'ProjectName',
  CompleteProfile: 'CompleteProfile',
  SelectOne: 'SelectOne',
  AuthProfile: 'AuthProfile',
  Where: 'Where',
  Interview: 'Interview',
  Chat: 'Chat',
  What: 'What',
  More: 'More',
  UploadProfile: 'UploadProfile',
  Profile: 'Profile',
  Projects: 'Projects',
  Candidate: 'Candidate',
  ProjectType: 'ProjectType',
  ProjectName: 'ProjectName',
  ProjectDetails: 'ProjectDetails',
  Message: 'Message',
  AuthVideoUpload: 'AuthVideoUpload',
  CandidateDetails: 'CandidateDetails',
  AuthPictureUpload: 'AuthPictureUpload',
  Notifications: 'Notifications',
  JobDescription: 'JobDescription',
  CreateProject: 'CreateProject',
  InterviewInvitations: 'InterviewInvitations',
  ProjectDescription: 'ProjectDescription',
  EditProfile: 'EditProfile',
  ForgotPassword: 'ForgotPassword',
  CreateProjectDetails: 'CreateProjectDetails',
};
